Phoenix v2 w/ RPC
dusk-network/phoenix-archived pull request #30
Opened 2020-04-08 17:57 UTC by vlopes11

2020-04-09 16:12 UTC, jules approved these changes

2020-04-09 16:13 UTC, jules requested changes

2020-04-09 16:13 UTC, jules commented on src/rpc/types.rs
> +impl From<Nullifier> for rpc::Nullifier {
I believe we already have a conversion implementation somewhere in the nullifier source file, and it seems that cargo is complaining about it as well

2020-04-09 16:30 UTC, krl approved these changes

2020-04-13 06:54 UTC, jules commented on src/crypto/merkle.rs
> +    pub fn new<T: MerkleProofProvider>(levels: [MerkleLevel; TREE_HEIGHT]) -> Self {
Do we still need `T`?

2020-04-15 19:45 UTC, jules approved these changes

2020-04-16 12:56 UTC, merged