Add few conversion for rpc's types, and `try_trait` feat.
dusk-network/phoenix-archived pull request #33
Opened 2020-04-15 08:49 UTC by ZER0

Those conversions are needed to have smaller code in the phoenix abi
conversion, since we convert Scalar types (and similar multiple times).

It simplify the code from:
```
  let value_commitment =
    note.value_commitment.as_ref().ok_or(Error::Generic)?;

    let mut value_commitment_buf = [0u8; 32];
    value_commitment_buf.copy_from_slice(&value_commitment.data);
```

to:

```
value_commitment: note.value_commitment.as_ref()?.into()
```

2020-04-15 09:13 UTC, vlopes11 requested changes

2020-04-15 09:13 UTC, vlopes11 commented on src/rpc/types.rs
> +        buf.copy_from_slice(&s.data);
For scalars, we should use `utils::serialize_bls_scalar` and `utils::deserialize_bls_scalar`

We will change the scalar type in the near future, and with that we always serialize and deserialize safely.

A malicious user can send a slice of bytes with less or more than 32 bytes, and this way he will lead to a panic on the server.

Also, the `utils` implementation will serialize and deserialize on canonical form.

2020-04-17 11:38 UTC, CPerezz commented on src/rpc/types.rs
> +        buf.copy_from_slice(&s.data);
Currently you can use the Serde implementations I added for `Scalar` which are included in `bls12_381` `master`

2020-04-20 11:20 UTC, ZER0 commented
Closing because, as discussed with @vlopes11, for the time being those are not necessary anymore.

2020-04-20 11:20 UTC, closed without merging