Refactor gadgets
dusk-network/phoenix-archived pull request #54
Opened 2020-06-09 09:07 UTC by Bounce23

The gadgets in the PLONK library have changed format since the initial phoenix implementation and the way in which phoenix interacts with the composer will be altered in this PR. 

This closes #48.

2020-06-16 13:03 UTC, krl commented
@CPerezz is this something we should merge? if you rebase it on master after #55, it should also pass the tests.

@Bounce23 also please check if you can rebase this on master and have some of the ignored tests actually pass.

2020-06-16 13:35 UTC, CPerezz commented
No, we should not merge this. Indeed it should be set as draft PR atm. @Bounce23 @julesdesmit

2020-06-22 08:10 UTC, CPerezz requested changes
Some nits and things which need extra explanations.

2020-06-22 08:10 UTC, CPerezz commented on src/note/obfuscated.rs
> +        let value_commitment = crypto::sponge_hash(&[value_commitment, blinding_factor]);
As we discussed. The value commitment has nothing to do with a Hash. I belive this is still true, so this should not be done like this.

2020-06-22 08:10 UTC, CPerezz commented on src/note/transparent.rs
> +        let value_commitment = crypto::sponge_hash(&[value_commitment, blinding_factor]);
Same as avobe.

2020-06-22 08:10 UTC, CPerezz commented on src/transaction/mod.rs
> +pub const MAX_NOTES_PER_TRANSACTION: usize = 4 + 2;
This should be 8. Remember all of the variants Togh described in the specs.

2020-06-22 08:10 UTC, CPerezz commented on src/transaction/mod.rs
>  pub const MAX_OUTPUT_NOTES_PER_TRANSACTION: usize = 2;
Should be 4 also according to the specs.

2020-06-22 08:10 UTC, CPerezz commented on src/transaction/mod.rs
> +        // self.proof.replace(proof);
This should not be commented out. If any gadget (such as the commitment one) is not ready and/or mocked, we just use it here even it doesn't do anything.

2020-06-22 08:10 UTC, CPerezz commented on src/transaction/mod.rs
> +        Ok(())
Same as avobe.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/merkle.rs
> +        let index = 567;
What about setting the index as a random? On that way we get more chances to see that failing if there's any issue with the impl that we're missing.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/mod.rs
>  #[cfg(feature = "circuit-sanity")]
I'm not sure at all about why we need to have the gadgets as `cfg_features`. We will always use them, so for me this just adds complexity that we don't need.

Maybe @vlopes11 knows the reason that triggered this way of implementing this. But I don't see why this would be needed.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/preimage.rs
> +// }
If this is not needed, should be deleted.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/range.rs
> +pub fn range<T: TransactionItem>(composer: &mut StandardComposer, item: &T) {
Should  be documented. Since it just wraps over an existing function without explanation.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/range.rs
> +        let mut composer = StandardComposer::new();
If you're just wrapping over `range_gate` fn from PLONK, there's no need to test it since it is already done in the PLONK repo.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/sanity.rs
> +pub fn sanity(composer: &mut StandardComposer) {
The docs here are not inline with the circuit that you're doing. 

i don't see the utility of the circuit TBH since just constraints two values that are equal always.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/sk_r.rs
>  // use std::mem;
Should be removed.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/gadgets/sk_r.rs
> +pub fn sk_r()
Why do we need 20k+ Public inputs?? This statement is totally wrong for sure. 

Also, which is the purpose of this fn? Can't you just use the ecc_gate from PLONK once it's done? Does it really need a wrapper?

2020-06-22 08:10 UTC, CPerezz commented on src/zk/mod.rs
> +// use merlin::Transcript;
If this is not used, should be removed.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/mod.rs
> +// }
Not sure this is needed. You are wrapping a single line function. So I don't see the point.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/mod.rs
> +// }
If this is not used, remove it.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/public_inputs.rs
>              .iter()
Instead of going on this direction, why don't we set as `const` every position of the PI? Then we just need to allocate on the vector on the positions defined with the `const`.

2020-06-22 08:10 UTC, CPerezz commented on src/zk/tests.rs
>      let sk = SecretKey::default();
This can be removed. The proof serialization tests are performed in PLONK.

2020-06-22 08:18 UTC, julesdesmit commented on src/note/obfuscated.rs
> +        let value_commitment = crypto::sponge_hash(&[value_commitment, blinding_factor]);
I've dedicated a separate branch for fixing this inconsistency. It relies as well on the previously mentioned dusk-protobuf PR, so I will merge in the right changes in a different PR.

2020-06-22 08:18 UTC, julesdesmit commented on src/note/transparent.rs
> +        let value_commitment = crypto::sponge_hash(&[value_commitment, blinding_factor]);
Same reply :)

2020-06-22 08:19 UTC, julesdesmit commented on src/transaction/mod.rs
> +pub const MAX_NOTES_PER_TRANSACTION: usize = 4 + 2;
I thought we did max 4 input notes, max 2 output notes, which creates 4 * 2 = 8 variants?

2020-06-22 08:42 UTC, julesdesmit commented on src/zk/gadgets/merkle.rs
> +        let index = 567;
Good idea, will add it.

2020-06-22 09:08 UTC, julesdesmit commented on src/zk/gadgets/mod.rs
>  #[cfg(feature = "circuit-sanity")]
True, I went along with it mainly for consistency, but it makes sense.

2020-06-22 09:09 UTC, julesdesmit commented on src/zk/gadgets/sanity.rs
> +pub fn sanity(composer: &mut StandardComposer) {
Yeah, according to @vlopes11 it was used to put the public inputs in the right order. We decided to keep this gadget around for the time being, in case we would need it in the circuits, but I don't imagine we will keep it.

2020-06-22 09:27 UTC, julesdesmit commented on src/zk/gadgets/sk_r.rs
> +pub fn sk_r()
No clue, I didn't write that comment.

I think the most use this has is so that we can put it in the circuits and have the logic implemented later, so that it automatically works without changing the circuit. However, we can probably just add a commented line for the `ecc_gate` function instead.

2020-06-22 09:29 UTC, julesdesmit commented on src/zk/public_inputs.rs
>              .iter()
At the moment, I'm not sure where the positions will be since the circuit will be different to the old one. We can do it later on though.

2020-06-22 09:29 UTC, julesdesmit commented on src/zk/tests.rs
>      let sk = SecretKey::default();
Gotcha

2020-06-22 10:28 UTC, CPerezz commented on src/note/obfuscated.rs
> +        let value_commitment = crypto::sponge_hash(&[value_commitment, blinding_factor]);
Then let's merge the other PR before. Since this can't be merged IMO since it's not the correct behaviour.

2020-06-22 10:28 UTC, CPerezz commented on src/transaction/mod.rs
> +pub const MAX_NOTES_PER_TRANSACTION: usize = 4 + 2;
you're right. My bad.

2020-06-22 10:29 UTC, CPerezz commented on src/zk/gadgets/sanity.rs
> +pub fn sanity(composer: &mut StandardComposer) {
If you want to keep it then you'll need to refactor the gadgets to work with this. 

My suggestion is not to do it and hardcorde the positions.

2020-06-22 10:29 UTC, julesdesmit commented on src/note/obfuscated.rs
> +        let value_commitment = crypto::sponge_hash(&[value_commitment, blinding_factor]);
Cool, I will then merge it into this PR once the protobuf PR is done.

2020-06-22 10:29 UTC, CPerezz commented on src/zk/gadgets/sk_r.rs
> +pub fn sk_r()
Seems more reasonable!

2020-06-22 10:30 UTC, CPerezz commented on src/zk/public_inputs.rs
>              .iter()
kk. Then we should remove this since it's not going to be used.

2020-06-22 10:36 UTC, julesdesmit commented on src/zk/gadgets/sanity.rs
> +pub fn sanity(composer: &mut StandardComposer) {
Cool, then I will remove it.

2020-06-22 10:39 UTC, julesdesmit commented on src/zk/public_inputs.rs
>              .iter()
Will do

2020-06-23 10:21 UTC, CPerezz approved these changes
LGTM

2020-06-23 16:03 UTC, merged